### PR TITLE
fix: use context.data for both GET and POST

### LINKED ISSUE #16: support json POST body

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #16

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -45,11 +46,10 @@ async function main(req, context) {
     AWS_S3_REGION, AWS_S3_ACCESS_KEY_ID, AWS_S3_SECRET_ACCESS_KEY,
     HTTP_TIMEOUT_EXTERNAL,
   } = env;
-  const { searchParams } = new URL(req.url);
-  const params = Object.fromEntries(searchParams.entries());
+
   const {
     owner, repo, ref, path, prefix = 'live',
-  } = params;
+  } = context.data;
```
Comment (dominique-pfister) [inline src/index.js:52]: As it turns out, `context.data` contains the querystring params *even* when the request has no body

File: test/index.test.js [hunk 2]
```diff
@@ -100,7 +100,7 @@ describe('Index Tests', () => {
       AWS_S3_REGION: 'foo',
       AWS_S3_ACCESS_KEY_ID: 'bar',
       AWS_S3_SECRET_ACCESS_KEY: 'baz',
-    });
+    }, true);
```
Comment (dominique-pfister) [inline test/index.test.js:103]: To ensure all call conventions work, pass the parameters for that call as POST

**Review by tripodsan — APPROVED** [review]
