### PR TITLE
fix: use single bucket for content-bus

### LINKED ISSUE #88: use single bucket for content-bus
### BREAKING CHANGE

- use single bucket: `helix-content-bus`
- remove `h3` from content-bus id
- format: `s3://helix-content-bus/{contentBusId}/{contentBusPartition}/{path}`

### PR DESCRIPTION
**Pull request by tripodsan**
BREAKING CHANGE: content is no longer stored in individual buckets but
  inside a common helix-content-bus bucket.
  the content-bus id prefix was modified to not include the `h3` prefix.

fixes #88

### CODE REVIEW

File: src/storage.js [hunk 1]
```diff
@@ -280,6 +195,32 @@ class AWSStorage {
     log.info(`Object uploaded to: ${this.bucket}/${key}`);
   }
 
+  /**
+   * Store an object contents, along with headers.
```
Comment (dominique-pfister) [inline src/storage.js:199]: The jsdoc for this method has been copied from `store(key, res)`, which surprisingly makes it only 50% wrong; it should probably say: `store some data along with optional metadata to S3` while the other method should say `store a *response* along with headers to S3`

**Review by dominique-pfister — APPROVED** [review]

**Comment by tripodsan** [comment]
this PR is obsolete because its functionality was moved to helix-admin: https://github.com/adobe/helix-admin/pull/107
